### ISSUE TITLE
CI error in v0.2.7 release

### ISSUE THREAD

**Issue by tuyennhv** [ChainSafe/blst-ts#77]
**Describe the bug**

Found this in the CI releasing v0.2.7 https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945 although the CI was a success overall

```
33s
Run yarn config set ignore-engines true
yarn config v[1](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:1).22.19
success Set "ignore-engines" to "true".
Done in 0.0[7](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:8)s.
yarn run v1.22.19
$ yarn install --ignore-scripts && yarn build && yarn install
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
$ tsc --project tsconfig.build.json
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ node dist/scripts/install.js
Retrieving BLST native bindings /home/runner/work/blst-ts/blst-ts/prebuild/linux-x64-10[8](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:9)-binding.node ...
Error: Error importing BLST native bindings: 404 Not Found
Building BLST native bindings /home/runner/work/blst-ts/blst-ts/prebuild/linux-x64-108-binding.node from source...
BLST_WRAP_CPP_PREBUILD /home/runner/work/blst-ts/blst-ts/prebuild/blst_wrap.cpp exists, SWIG will be skipped
    at Object.downloadReleaseAsset (/home/runner/work/blst-ts/blst-ts/dist/scripts/downloadReleaseAsset.js:22:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:10)5:5)
    at async Object.downloadBindings (/home/runner/work/blst-ts/blst-ts/dist/scripts/downloadBindings.js:9:5)
    at async install (/home/runner/work/blst-ts/blst-ts/dist/scripts/install.js:34:9)
Launching node-gyp {
  nodeJsExec: '/opt/hostedtoolcache/node/18.12.1/x64/bin/node',
  nodeGypExec: '/home/runner/work/blst-ts/blst-ts/node_modules/node-gyp/bin/node-gyp.js',
  cwd: '/home/runner/work/blst-ts/blst-ts/blst/bindings/node.js',
  BLST_WRAP_CPP_PREBUILD: '/home/runner/work/blst-ts/blst-ts/prebuild/blst_wrap.cpp'
}
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.12.1 | linux | x64
gyp info find Python using Python version 3.[10](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:11).6 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v18.[12](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:13).1/node-v18.12.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v18.12.1/node-v18.12.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v18.12.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/runner/work/blst-ts/blst-ts/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/blst-ts/blst-ts/blst/bindings/node.js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/work/blst-ts/blst-ts/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/runner/.cache/node-gyp/18.12.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/runner/.cache/node-gyp/18.12.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/runner/work/blst-ts/blst-ts/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/runner/.cache/node-gyp/18.12.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/runner/work/blst-ts/blst-ts/blst/bindings/node.js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/runner/work/blst-ts/blst-ts/blst/bindings/node.js/build'
  ACTION binding_gyp_blst_target_blst_wrap Release/obj.target/blst/geni/blst_wrap.cpp
Copying and using '/home/runner/work/blst-ts/blst-ts/prebuild/blst_wrap.cpp'
  CXX(target) Release/obj.target/blst/geni/blst_wrap.o
  CC(target) Release/obj.target/blst/../../src/server.o
  CC(target) Release/obj.target/blst/../../build/assembly.o
  SOLINK_MODULE(target) Release/obj.target/blst.node
  COPY Release/blst.node
make: Leaving directory '/home/runner/work/blst-ts/blst-ts/blst/bindings/node.js/build'
gyp info ok 
Successfully built BLST native bindings from source
Done in 33.[14](https://github.com/ChainSafe/blst-ts/actions/runs/3706833809/jobs/6285801945#step:5:15)s.
```

**Expected behavior**

- No error
- Not sure if this is a real issue

**Comment by matthewkeil** [comment]
Stale issue resolved with rebuild. Closing
