### ISSUE TITLE
Installation fails on macOS 13.3.1

### ISSUE THREAD

**Issue by faustbrian** [ChainSafe/blst-ts#87]
Trying to install `0.2.6` but also later releases fails on macOS 13.3.1

```bash
pnpm i
Scope: all 112 workspace projects
packages/bep-033                         |  WARN  deprecated @npmcli/move-file@1.1.2
Packages: +1234
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1276, reused 1231, downloaded 0, added 0, done
node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst: Running install script, failed in 673ms
.../node_modules/@chainsafe/blst install$ node dist/scripts/install.js
│ Retrieving BLST native bindings /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/prebuild/darwin-arm64-108-binding.node ...
│ Error: Error importing BLST native bindings: 404 Not Found
│     at Object.downloadReleaseAsset (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/dist/scripts/downloadReleaseAsset.js:22:15)
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Object.downloadBindings (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/dist/scripts/downloadBindings.js:9:5)
│     at async install (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/dist/scripts/install.js:34:9)
│ Building BLST native bindings /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/prebuild/darwin-arm64-108-binding.node from source...
│ BLST_WRAP_CPP_PREBUILD /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/prebuild/blst_wrap.cpp exists, SWIG will be skipped
│ Launching node-gyp {
│   nodeJsExec: '/Users/brianfaust/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/node',
│   nodeGypExec: '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js',
│   cwd: '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js',
│   BLST_WRAP_CPP_PREBUILD: '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/prebuild/blst_wrap.cpp'
│ }
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.4.1
│ gyp info using node@18.14.1 | darwin | arm64
│ gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
│ gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Library/Caches/node-gyp/18.14.1/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/brianfaust/Library/Caches/node-gyp/18.14.1',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/brianfaust/Library/Caches/node-gyp/18.14.1/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│   ACTION binding_gyp_blst_target_blst_wrap Release/obj.target/blst/geni/blst_wrap.cpp
│ /bin/sh: python: command not found
│ make: *** [Release/obj.target/blst/geni/blst_wrap.cpp] Error 127
│ gyp ERR! build error
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/lib/build.js:194:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Darwin 22.4.0
│ gyp ERR! command "/Users/brianfaust/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/node" "/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js
│ gyp ERR! node -v v18.14.1
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok
│ Error: Error building BLST native bindings: Command failed: /Users/brianfaust/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/node /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js rebuild
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.4.1
│ gyp info using node@18.14.1 | darwin | arm64
│ gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
│ gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
│ gyp info spawn args [
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/brianfaust/Library/Caches/node-gyp/18.14.1/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/brianfaust/Library/Caches/node-gyp/18.14.1',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/brianfaust/Library/Caches/node-gyp/18.14.1/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│ /bin/sh: python: command not found
│ make: *** [Release/obj.target/blst/geni/blst_wrap.cpp] Error 127
│ gyp ERR! build error
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/lib/build.js:194:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Darwin 22.4.0
│ gyp ERR! command "/Users/brianfaust/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/node" "/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/blst/bindings/node.js
│ gyp ERR! node -v v18.14.1
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok
│     at ChildProcess.exithandler (node:child_process:419:12)
│     at ChildProcess.emit (node:events:513:28)
│     at maybeClose (node:internal/child_process:1091:16)
│     at Socket.<anonymous> (node:internal/child_process:449:11)
│     at Socket.emit (node:events:513:28)
│     at Pipe.<anonymous> (node:net:322:12) {
│   code: 1,
│   killed: false,
│   signal: null,
│   cmd: '/Users/brianfaust/Library/Application Support/fnm/node-versions/v18.14.1/installation/bin/node /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/bin/node-gyp.js rebuild'
│ }
│ Error: Error downloading and building BLST native bindings /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/prebuild/darwin-arm64-108-binding.node. No fallback
│     at install (/Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst/dist/scripts/install.js:61:11)
└─ Failed in 673ms at /Users/brianfaust/Developer/bearmint/bearmint/node_modules/.pnpm/@chainsafe+blst@0.2.8/node_modules/@chainsafe/blst
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by matthewkeil** [comment]
Hi @faustbrian, the error mentions `/bin/sh: python: command not found`.  Recent versions of OSX ship with `python3` and the `python` command  (python 2 is what node-gyp looks for by default) is not automatically on the `PATH`.  Please verify if that is the case with `which python` and if so, the easiest way to resolve is using `pyenv` to manage versions of Python.

**Comment by faustbrian** [comment]
Duh, that was it. Thanks!

**Comment by 0toierance** [comment]
A slightly easier solution was using symbolic linking.    sudo ln -s /usr/bin/python3 /usr/bin/python
